# Travis CI credentials

language: scala

services:
    - mysql

sudo: false

scala:
 - "2.10.5"
 - "2.11.7"

# Emails to notify
notifications:
  slack:
    rooms:
      - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k

  email:
  - dev@websudos.com

# Branches to build.
branches:
  only:
    - master
    - develop

sudo: false

jdk:
  - oraclejdk7
  - openjdk7


before_script:
  - mysql -e "CREATE DATABASE morpheus-test;"
  - mysql -e "CREATE USER 'morpheus'@'localhost' IDENTIFIED BY 'morpheus23!';"

script: "sbt clean coverage test"

